config/routes.rb
Rails.application.routes.draw do
  # get 'finder/index'

  # get 'finder/alphabetized'

  # get 'finder/missing_email'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'finder#index'
  # resources 'customers', only: [:index]
  get '/customers/missing_email' => 'finder#missing_email', as: "missing_email"
  get '/customers/alphabetized' => 'finder#alphabetized', as: "alphabetized"
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  belongs_to :province
  validates :full_name, presence: true, length: {minimum: 2}
end

app/models/province.rb
class Province < ApplicationRecord
  has_many :customers
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/finder_controller.rb
class FinderController < ApplicationController
  def index
    @customers = Customer.all  
  end

  def alphabetized
    @customers = Customer.all.order(:full_name)
  end

  def missing_email
    @customers = Customer.where("email = ''")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/finder_helper.rb
module FinderHelper
end

app/views/customers/_customer.html.slim
/ ''= render @customers' in index to render this partial
/ ''= render @customer' in show to render this partial
/ Full expanded version: '= render partial: 'customer', collection: @customers, locals: {full_details: false}
.customer
  h2#bold = customer.full_name
  = image_tag customer.image  
  div
    strong Phone: 
    = customer.phone_number
  div
    strong Province: 
    / - @province = customer.province_id
    - if customer.province.present?
      = customer.province.name
    - else
      | None
  div
    strong Email: 
    span#underline = customer.email    
  div
    strong Notes: 
    = customer.notes

app/views/finder/alphabetized.html.slim
h1 All Customers - By Name
li
  ul = link_to 'New Customer', new_admin_customer_path
  ul = link_to 'Missing Email', missing_email_path
  ul = link_to 'All Customers', root_path
= render partial: '/customers/customer', collection: @customers

app/views/finder/index.html.slim
h1 All Customers
li
  ul = link_to 'New Customer', new_admin_customer_path
  ul = link_to 'Missing Email', missing_email_path
  ul = link_to 'Alphabetized', alphabetized_path
= render partial: '/customers/customer', collection: @customers

app/views/finder/missing_email.html.slim
h1 Customers without Email Address
li
  ul = link_to 'New Customer', new_admin_customer_path
  ul = link_to 'Alphabetized', alphabetized_path
  ul = link_to 'All Customers', root_path
= render partial: '/customers/customer', collection: @customers

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CRM</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>